apiVersion: v1
kind: Service
metadata:
  name: panw-policy 
  labels:
    app: panw-policy 
spec:
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 9080 
    targetPort: 9080 
  selector:
    app: panw-policy 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: panw-policy 
spec:
  selector:
    matchLabels:
      app: panw-policy
  replicas: 1
  template:
    metadata:
      labels:
        app: panw-policy 
    spec:
      containers:
        - name: panw-policy 
          image: vinayvenkat/panw_policy_api_config_map
          command: ["/go/src/panw/panw_policy_api"]
          ports:
          - containerPort: 9080
          volumeMounts:
          - name: config-volume 
            mountPath: /etc/config
      volumes:
       - name: "config-volume"
         configMap: 
           name: panw-security-policies 
